# filepath: [cassandra-app.yaml](http://_vscodecontentref_/3)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: cassandra
    targetRevision: 12.3.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/GeorgOfenbeck/bigDataStackTraffic/main/cassandra/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cassandra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
