apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
---
# filepath: [cassandra-app.yaml](http://_vscodecontentref_/3)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: cassandra
    targetRevision: 11.0.0
    helm:
      values: |                                 # Inline the values.yaml content here
        # Example values from values.yaml
        persistence:
          size: 2Gi
          commitLogsize: 1Gi
        resources:
          limits:
            cpu: 2
            memory: 3Gi
          requests:
            cpu: 2
            memory: 2Gi
        maxHeapSize: 2G
        newHeapSize: 1G

  destination:
    server: https://kubernetes.default.svc
    namespace: cassandra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
