apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Use the Bitnami Helm repository for the chart
    chart: kafka                                # Specify the Helm chart name
    targetRevision: 30.0.0
    helm:
      values: |                                 # Inline the values.yaml content here
        # Example values from values.yaml
        listeners:
          client:
            protocol: 'PLAINTEXT'
          controller:
            protocol: 'PLAINTEXT'
        service:
          type: LoadBalancer
          port: 
            external: 9094
        controller:
          replicaCount: 2
 
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
