apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Use the Bitnami Helm repository for the chart
    chart: kafka                                # Specify the Helm chart name
    targetRevision: 15.2.2                      # Specify the chart version (optional)
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/GeorgOfenbeck/bigDataStackTraffic/main/kafka/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
