# filepath: [postgres-app.yaml](http://_vscodecontentref_/4)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.6.2
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/GeorgOfenbeck/bigDataStackTraffic/main/postgres/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
