apiVersion: v1
kind: Namespace
metadata:
  name: kafka-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scala-kafka-consumer
  namespace: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scala-kafka-consumer
  template:
    metadata:
      labels:
        app: scala-kafka-consumer
    spec:
      containers:
      - name: scala-kafka-consumer
        image: ofenbeck/scalaflinkconsumer:x2
        ports:
        - containerPort: 8080
        - containerPort: 8081
