# filepath: [spark-app.yaml](http://_vscodecontentref_/2)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: spark
    targetRevision: 6.1.3
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/GeorgOfenbeck/bigDataStackTraffic/main/spark/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
