
version: '4.8'

services:
  jupyter:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: jupytergpu
    ports:
      - "8889:8888"
    volumes:
      - ./notebooks:/tf/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=zrdp
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
