apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      component: datanode
  template:
    metadata:
      labels:
        app: hadoop
        component: datanode
    spec:
      containers:
      - name: datanode
        image: sbloodys/hadoop:3.3.6
        command: ["hdfs", "datanode"]
        envFrom:
        - configMapRef:
            name: hadoop-config
        livenessProbe:
          httpGet:
            path: /
            port: 9864
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: hadoop-config
          mountPath: /etc/hadoop/conf
      volumes:
      - name: datanode-storage
        emptyDir: {}
      - name: hadoop-config
        configMap:
          name: hadoop-config
      initContainers:
      - name: wait-for-namenode
        image: busybox
        command: ['sh', '-c', 'until nc -z namenode 9870; do sleep 1; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bigdata
spec:
  ports:
  - port: 9864
    targetPort: 9864
  selector:
    app: hadoop
    component: datanode
