
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      component: resourcemanager
  template:
    metadata:
      labels:
        app: hadoop
        component: resourcemanager
    spec:
      containers:
      - name: resourcemanager
        image: sbloodys/hadoop:3.3.6
        command: ["yarn", "resourcemanager"]
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: hadoop-config
        livenessProbe:
          httpGet:
            path: /
            port: 8088
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: bigdata
spec:
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: hadoop
    component: resourcemanager
