apiVersion: v1
kind: Namespace
metadata:
  name: bigdata

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  namespace: bigdata
spec:
  ports:
    - port: 9870
      name: web
      targetPort: 9870
  selector:
    app: hadoop-namenode

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
        - name: hadoop-namenode
          image: ghcr.io/apache/hadoop:3.3.6
          command: ["hdfs", "namenode"]
          ports:
            - containerPort: 9870
          env:
            - name: ENSURE_NAMENODE_DIR
              value: "/tmp/hadoop-root/dfs/name"
          volumeMounts:
            - name: hadoop-namenode-storage
              mountPath: /hadoop/dfs/name
      volumes:
        - name: hadoop-namenode-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  namespace: bigdata
spec:
  ports:
    - port: 9864
      name: web
      targetPort: 9864
  selector:
    app: hadoop-datanode

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-datanode
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
        - name: hadoop-datanode
          image: ghcr.io/apache/hadoop:3.3.6
          command: ["hdfs", "datanode"]
          ports:
            - containerPort: 9864
          volumeMounts:
            - name: hadoop-datanode-storage
              mountPath: /hadoop/dfs/data
      volumes:
        - name: hadoop-datanode-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: bigdata
spec:
  ports:
    - port: 7077
      name: spark
      targetPort: 7077
    - port: 8080
      name: web
      targetPort: 8080
  selector:
    app: spark-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: ofenbeck/spark-master:3.5.4-hadoop3.4.1
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: PYSPARK_PYTHON
              value: python3

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: bigdata
spec:
  ports:
    - port: 8081
      name: web
      targetPort: 8081
  selector:
    app: spark-worker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: bigdata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: ofenbeck/spark-worker:3.5.4-hadoop3.4.1
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_MASTER
              value: spark://spark-master:7077
