# filepath: kafka/values.yaml
global:
  defaultStorageClass: "microk8s-hostpath"
service:
  type: LoadBalancer
  port: 
    external: 9094

controller:
  ## @param controller.replicaCount Number of Kafka controller-eligible nodes
  ##
  replicaCount: 2
