# Example values from values.yaml
listeners:
  client:
    protocol: 'PLAINTEXT'
  controller:
    protocol: 'PLAINTEXT'
service:
  type: LoadBalancer
  port: 
    external: 9094
controller:
  replicaCount: 2
